[package]
name = "thread"
version = "0.1.0"
authors = ["luc", "boc"]
edition = "2021"

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = "=1.2.7"
cosmwasm-storage = "=1.2.7"
cosmwasm-schema = "=1.2.7"

member = { path = "../member", default-features = false, version = "*" }
shared = { path = "../shared", default-features = false, version = "*" }
