[package]
name = "thread"
version = "0.2.0"
authors = ["luc", "boc"]
edition = "2021"

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = "1.1"
cosmwasm-storage = "1.1"
cosmwasm-schema = "1.1"

member = { path = "../member", default-features = false, version = "*" }
shared = { path = "../shared", default-features = false, version = "*" }
